columns: 
  -id: int
  -Gender : category
  -Age : int
  -Driving_licence : caint 
  -Region_code : float 
  -Previously_Insured : int 
  -Vehicle_Age : category 
  -Vehicle_Damage : category 
  -Annual_premium : float 
  -Policy_Sales_Channel : float 
  -Vintage : int 
  -Response : int 


numerical_columns: 
  - Age
  - Driving_licence  
  - Region_code  
  - Previously_Insured    
  - Annual_Premium  
  - Policy_Sales_Channel  
  - Vintage  
  - Response

categorical_columns:  
  - Gender 
  - Vehicle_Age 
  - Vehicle_Damage


drop_columns : _id

# for data transformation 
num_features: 
  - Age 
  - Vintage 

mm_columns : 
  - Annual_Premium
